#!/usr/bin/env bash
# Configure Nginx to run as nginx user and listen on port 8080

sed -i 's/^user .*/user nginx;/g' /etc/nginx/nginx.conf
echo -e "server {\n    listen 8080 default_server;\n    listen [::]:8080 default_server;\n    server_name _;\n\n    location / {\n        # Configuration for serving content\n        # ...\n    }\n}" >> /etc/nginx/nginx.conf
nginx -s reload
